### ISSUE TITLE
Requests dependencies issue in Colab again

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/kso#232]
I am afraid the current dev version is still having the same ["requests" depency issue we had a while back](https://github.com/ocean-data-factory-sweden/kso-data-management/issues/66)

**Comment by victor-wildlife** [comment]
![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/b9175e27-d68a-43a2-afa7-9f9c785e167e)

**Comment by jannesgg** [comment]
@victor-wildlife After looking into options to fix this, including trying to pin a version of google-colab to install, it seems that restarting the kernel is the only viable solution. I also looked into upgrading the version of panoptes, but even the latest version requires requests to be below 2.29.

My suggestion would be to tell users to restart the kernel if they encounter this error. Might be best to say "Restart the kernel and then run the "Import Python packages" cell again". 

We might have to modify that cell a bit though so that it works after the restart, here is a proposal: 

`# Set the directory of the libraries
import sys
try:
  
  if "kso_utils" not in sys.modules:
      sys.path.append("..")
      import kso_utils.kso_utils

      sys.modules["kso_utils"] = kso_utils.kso_utils
      print("Using development version...")
      # Enables testing changes in utils
      %load_ext autoreload
      %autoreload 2

  else:
    pass
  
except:
    print("Installing latest version from PyPI...")
    %pip install -q kso-utils


# Import required modules
import kso_utils.tutorials_utils as t_utils
import kso_utils.project_utils as p_utils
import kso_utils.widgets as kso_widgets
from kso_utils.project import ProjectProcessor


print("Packages loaded successfully")`

What do you think?

**Comment by victor-wildlife** [comment]
Thanks @jannesgg 
I have coded a potential solution of the first cell https://codefile.io/f/t23FT730Vr but after I ran it successfully, I got the following torch error in the second cell. Any thoughts?

![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/7671ce45-04bb-429c-a00d-7818c01f9b96)

**Comment by victor-wildlife** [comment]
Also, it seems like the panoptes package might solve our request conflict issues https://github.com/zooniverse/panoptes-python-client/pull/301
